version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'quarterly'
    cooldown:
      default-days: 7
    groups:
      gha-updates:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the following directories
    directories:
      - '/'
      - '/components'
      - '/sandbox'
      - '/tasks-list'
      - '/templates-list'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
    ignore:
      - dependency-name: 'lint-staged'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
