import adapter from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
		alias: {
			'fractal-components': './components/src/lib'
		},
		typescript: {
			// Customize generated .svelte-kit/tsconfig.json
			config: (/** @type {Record<string, any>} */ cfg) => {
				// Add __tests__ folder to includes list
				cfg.include.push('../__tests__/**/*.js');
				// Add extra matchers to Assertion<HTMLElement>
				cfg.compilerOptions.types = ['@testing-library/jest-dom'];
				return cfg;
			}
		},
		csp: {
			directives: {
				'script-src': [
					// Trust script elements using hashes or nonces, then trust script elements dynamically generated by them
					'strict-dynamic',
					// Needed by AJV, see https://ajv.js.org/security.html#content-security-policy
					'unsafe-eval',
					// From CSP Evaluator: Consider adding 'unsafe-inline' (ignored by browsers supporting nonces/hashes) to be backward compatible with older browsers.
					// Causes "Ignoring 'unsafe-inline'" warning in Firefox
					'unsafe-inline',
					// From CSP Evaluator: Consider adding https: and http: url schemes (ignored by browsers supporting 'strict-dynamic') to be backward compatible with older browsers.
					// Causes warnings in Firefox
					'https:',
					'http:'
				],
				// Fallback policy for not defined rules: by default forbid everything that is not defined
				'default-src': ['none'],
				// Control fetch requests and WebSocket connections
				'connect-src': ['self'],
				// Load images from self and images with src="data:image/..."
				'img-src': ['self', 'data:'],
				// Styles (CSS)
				'style-src': ['self', 'unsafe-inline'],
				// Fonts
				'font-src': ['self'],
				// Restrict form submissions to self
				'form-action': ['self'],
				// Forbid embedding in frames
				'frame-ancestors': ['none'],
				// Allow only frames loading from self
				'frame-src': ['self'],
				// Forbid <object> and <embed> tag
				'object-src': ['none'],
				// Forbid uri in <base> tag
				'base-uri': ['none']
			}
		}
	}
};

export default config;
