import adapter from '@sveltejs/adapter-node';
import { sveltekit } from '@sveltejs/kit/vite';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { defineConfig } from 'vitest/config';
import { svelteTesting } from '@testing-library/svelte/vite';

const packageJsonFile = fileURLToPath(new URL('package.json', import.meta.url));
const packageJsonData = readFileSync(packageJsonFile);
const pkg = JSON.parse(packageJsonData.toString());

/** @type {import('vite').UserConfigExport} */ const config = defineConfig({
	plugins: [
		sveltekit({
			adapter: adapter(),
			csp: {
				directives: {
					'script-src': [
						// Trust script elements using hashes or nonces, then trust script elements dynamically generated by them
						'strict-dynamic',

						// Needed by AJV, see https://ajv.js.org/security.html#content-security-policy
						'unsafe-eval',

						// From CSP Evaluator: Consider adding 'unsafe-inline' (ignored by browsers supporting nonces/hashes) to be backward compatible with older browsers.
						// Causes "Ignoring 'unsafe-inline'" warning in Firefox
						'unsafe-inline',

						// From CSP Evaluator: Consider adding https: and http: url schemes (ignored by browsers supporting 'strict-dynamic') to be backward compatible with older browsers.
						// Causes warnings in Firefox
						'https:',
						'http:'
					],
					// Fallback policy for not defined rules: by default forbid everything that is not defined
					'default-src': ['none'],
					// Control fetch requests and WebSocket connections
					'connect-src': ['self'],
					// Load images from self and images with src="data:image/..."
					'img-src': ['self', 'data:'],
					// Styles (CSS)
					'style-src': ['self', 'unsafe-inline'],
					// Fonts
					'font-src': ['self'],
					// Restrict form submissions to self
					'form-action': ['self'],
					// Forbid embedding in frames
					'frame-ancestors': ['none'],
					// Allow only frames loading from self
					'frame-src': ['self'],
					// Forbid <object> and <embed> tag
					'object-src': ['none'],
					// Forbid uri in <base> tag
					'base-uri': ['none']
				}
			}
		}),
		svelteTesting()
	],
	define: { __APP_VERSION__: JSON.stringify(pkg.version) },
	build: { sourcemap: true },
	test: {
		globals: true,
		environment: 'jsdom',
		setupFiles: ['./vitest.setup.js'],
		include: ['**/__tests__/**/*\\.test\\.js'],
		exclude: ['components/**', 'node_modules', 'build', '.idea', '.git', '.cache'],
		coverage: {
			provider: 'istanbul',
			reporter: ['text', 'json', 'html'],
			reportsDirectory: './coverage-unit',
			include: ['src']
		}
	},
	// Tells Vite to allow serving files from the components folder when running npm run dev
	server: {
		fs: {
			allow: ['./components/src/lib']
		},
		proxy: {
			'/help': {
				target: 'http://localhost:8001',
				changeOrigin: true
			}
		}
	},
	optimizeDeps: {
		// The dependencies to be optimized are explicitly listed, to avoid the reloads triggered by their automatic detection
		include: [
			'clsx',
			'slim-select',
			'marked',
			'dompurify',
			'ajv/dist/ajv',
			'ajv/dist/2020',
			'ajv-formats',
			'json-diff-viewer-component',
			'bootstrap',
			'bootstrap-icons'
		]
	}
});

export default config;
