name: Vite Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:

  build:
    name: "Node ${{ matrix.node-version }}"
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ["16", "18"]


    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
