name: Check&Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  check_and_build:
    name: 'Node ${{ matrix.node-version }}'
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ['16', '18']

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run static code analysis
        run: npx eslint .

      - name: Run vitest tests
        run: npm run test

      - name: Build site
        env:
          FRACTAL_SERVER_HOST: http://localhost:8000
          AUTH_COOKIE_NAME: fastapiusersauth
          AUTH_COOKIE_SECURE: false
          AUTH_COOKIE_DOMAIN: localhost
          AUTH_COOKIE_PATH: /
          AUTH_COOKIE_MAX_AGE: 1800
          AUTH_COOKIE_SAME_SITE: lax
          AUTH_COOKIE_HTTP_ONLY: true
        run: npm run build
