name: docs

on: workflow_call

jobs:
  build:
    name: 'Build documentation'
    runs-on: ubuntu-24.04
    permissions: {}
    env:
      ENABLE_FRACTAL_LINKS: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Download playwright report artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: playwright-html-report-attempt-${{ github.run_attempt }}
          path: docs/playwright-report

      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
          version: '0.11.14'
          enable-cache: false
          python-version: '3.12'
      - run: uv sync --frozen
      - run: ./build-docs.sh
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install components dependencies
        run: |
          cd components
          npm ci
      - name: Install sandbox dependencies
        run: |
          cd sandbox
          npm ci
      - name: Build sandbox
        run: |
          cd sandbox
          npm run build
      - name: Move sandbox built files in docs site
        run: mv sandbox/build/ site/sandbox
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: 'site'

  deploy:
    name: 'Deploy docs'
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      # https://github.com/actions/deploy-pages?tab=readme-ov-file
      # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers#adding-permissions-settings
      pages: write # To create pages deployments when calling the GitHub API
      id-token: write # To request the OIDC JWT token
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        id: deployment
