name: End-to-end tests

on:
  push:
    branches: ['main', 'ihb-develop']
  pull_request:
    branches: ['main', 'ihb-develop']

permissions: {}

jobs:
  end_to_end_tests:
    name: 'E2E tests - Node ${{ matrix.node-version }} - ${{ matrix.browser }} ${{ matrix.shard-index }}'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      OAUTH_CLIENT_NAME: dexidp
      OAUTH_CLIENT_ID: client_test_web_id
      OAUTH_CLIENT_SECRET: client_test_web_secret
      OAUTH_REDIRECT_URL: 'http://localhost:5173/auth/login/oauth2/'
      OAUTH_OIDC_CONFIG_ENDPOINT: 'http://127.0.0.1:5556/dex/.well-known/openid-configuration'
      PUBLIC_OAUTH_CLIENT_NAME: dexidp
      PUBLIC_FRACTAL_DATA_URL: http://localhost:3000/data
      PUBLIC_FRACTAL_VIZARR_VIEWER_URL: http://localhost:3000/data/vizarr
      PUBLIC_FRACTAL_VOLE_VIEWER_URL: http://localhost/vole-viewer
      PUBLIC_FRACTAL_FEATURE_EXPLORER_URL: http://localhost:8501
      FRACTAL_RUNNER_BACKEND: local
      FRACTAL_DEFAULT_GROUP_NAME: All
      FRACTAL_ENABLE_TASK_GROUP_RESET: true
      PUBLIC_GUEST_USERNAME: guest@fractal.xy
      PUBLIC_GUEST_PASSWORD: guest

    strategy:
      matrix:
        node-version: ['24']
        browser: ['chromium', 'firefox']
        shard-index: [1, 2, 3]
        shard-total: [3]
      fail-fast: false

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fractal_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      oauth2:
        image: ghcr.io/fractal-analytics-platform/oauth@sha256:42c80e3193d8eb5a20b5c88a90c625b9ea45ef9f5228b6676ea0b0494bed3d9a # 0.1
        ports:
          - 5556:5556

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        timeout-minutes: 3
        run: npx playwright install --with-deps --only-shell ${{ matrix.browser }}

      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.browser }} --shard=${{ matrix.shard-index }}/${{ matrix.shard-total }}

      - name: Archive test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-folder-node-${{ matrix.node-version }}-${{ matrix.browser }}-${{ matrix.shard-index }}
          path: test-results
          retention-days: 7

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: blob-report-${{ matrix.node-version }}-${{ matrix.browser }}-${{ matrix.shard-index }}
          path: blob-report
          retention-days: 1

  merge-reports:
    name: 'E2E tests - Merge Reports'
    # Merge reports after end_to_end_tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [end_to_end_tests]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-html-report-attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7
