name: Create GitHub release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-c][0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

permissions: {}

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: gh release create "${GH_REF_NAME}" --draft --title "${GH_REF_NAME}"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF_NAME: ${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    needs: create-release-draft
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ['24']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Generate build artifacts
        run: npm run build

      - name: Generate the package
        run: npm pack

      - name: Extract the package
        run: tar -xzf fractal-web-*.tgz

      - name: Repack the package removing parent folder
        env:
          GH_REF_NAME: ${{ github.ref_name }}
        run: tar -C package -czf "node-${{ matrix.node-version }}-fractal-web-${GH_REF_NAME}.tar.gz" build package.json node_modules LICENSE

      - run: gh release upload "${GH_REF_NAME}" "node-${{ matrix.node-version }}-fractal-web-${GH_REF_NAME}.tar.gz"
        env:
          GH_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}

      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
        with:
          version: '0.11.14'
          enable-cache: false
          python-version: '3.12'
      - run: uv sync --frozen
      - name: Build Docs
        run: ./build-docs.sh
      - run: tar -czf docs-${GH_REF_NAME}.tar.gz site
        env:
          GH_REF_NAME: ${{ github.ref_name }}

      - run: gh release upload "${GH_REF_NAME}" "docs-${GH_REF_NAME}.tar.gz" --clobber
        env:
          GH_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}

  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: gh release edit "${GH_REF_NAME}" --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REF_NAME: ${{ github.ref_name }}
