name: Unit tests

on:
  push:
    branches: ['main', 'ihb-develop']
  pull_request:
    branches: ['main', 'ihb-develop']

permissions: {}

jobs:
  unit_tests:
    name: 'Unit tests - Node ${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ['24']
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install components dependencies
        run: |
          cd components
          npm ci

      - name: Run vitest tests on components module
        run: |
          cd components
          npm run test

      - name: Run vitest tests
        run: npx vitest run
        env:
          TZ: Europe/Rome
          LANG: it-IT
